//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaHall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CinemaHall()
        {
            this.SessionCinema = new HashSet<SessionCinema>();
        }
    
        public int CinemaHallID { get; set; }
        public string Name { get; set; }
        public int Сapacity { get; set; }
        public int Rows { get; set; }
        public int CountInRows { get; set; }
        public int TypeHallID { get; set; }
    
        public virtual TypeHall TypeHall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionCinema> SessionCinema { get; set; }
    }
}
