//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilmInfo()
        {
            this.FilmGenre = new HashSet<FilmGenre>();
            this.SessionCinema = new HashSet<SessionCinema>();
        }
    
        public int FilmID { get; set; }
        public string Name { get; set; }
        public int CountryID { get; set; }
        public int DirectorID { get; set; }
        public int DurationMin { get; set; }
        public int AgeRatingID { get; set; }
        public int StudioID { get; set; }
        public int LanguageID { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual AgeRating AgeRating { get; set; }
        public virtual Country Country { get; set; }
        public virtual Director Director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmGenre> FilmGenre { get; set; }
        public virtual Language Language { get; set; }
        public virtual Studio Studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionCinema> SessionCinema { get; set; }
    }
}
