//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaOnlineEntities2 : DbContext
    {
        public CinemaOnlineEntities2()
            : base("name=CinemaOnlineEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeRating> AgeRating { get; set; }
        public virtual DbSet<CinemaHall> CinemaHall { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<FilmGenre> FilmGenre { get; set; }
        public virtual DbSet<FilmInfo> FilmInfo { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SessionCinema> SessionCinema { get; set; }
        public virtual DbSet<Studio> Studio { get; set; }
        public virtual DbSet<Tiket> Tiket { get; set; }
        public virtual DbSet<TypeHall> TypeHall { get; set; }
        public virtual DbSet<TypeOperation> TypeOperation { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
