//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionCinema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionCinema()
        {
            this.Tiket = new HashSet<Tiket>();
        }
    
        public int SessionCinemaID { get; set; }
        public int idCinema { get; set; }
        public int idHalls { get; set; }
        public System.DateTime DateSession { get; set; }
    
        public virtual CinemaHall CinemaHall { get; set; }
        public virtual FilmInfo FilmInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiket> Tiket { get; set; }
    }
}
