//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiket
    {
        public int TiketsID { get; set; }
        public int SessionID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public decimal Price { get; set; }
        public int TypeOperation { get; set; }
        public int ClientID { get; set; }
    
        public virtual SessionCinema SessionCinema { get; set; }
        public virtual TypeOperation TypeOperation1 { get; set; }
        public virtual User User { get; set; }
    }
}
